public enum GatePolicy
{
	OpenableByFriendsExceptWhenInsideAndUnderAttack,
	OpenableByFriendsEvenWhenUnderAttack,
	NeverOpenable,
	CompletelyOpen,
	OpenableByCommunityExceptWhenInsideAndUnderAttack,
	OpenableByCommunityEvenWhenUnderAttack
}
