namespace PartyCSharpSDK;

public enum PARTY_DESTROYED_REASON : uint
{
	PARTY_DESTROYED_REASON_REQUESTED,
	PARTY_DESTROYED_REASON_DISCONNECTED,
	PARTY_DESTROYED_REASON_KICKED,
	PARTY_DESTROYED_REASON_DEVICE_LOST_AUTHENTICATION,
	PARTY_DESTROYED_REASON_CREATION_FAILED
}
