namespace PartyCSharpSDK;

public enum PARTY_TEXT_CHAT_FILTER_LEVEL : uint
{
	PARTY_TEXT_CHAT_FILTER_LEVEL_FAMILY_FRIENDLY,
	PARTY_TEXT_CHAT_FILTER_LEVEL_MEDIUM,
	PARTY_TEXT_CHAT_FILTER_LEVEL_MATURE
}
