namespace PartyCSharpSDK;

public enum PARTY_CHAT_PERMISSION_OPTIONS : uint
{
	PARTY_CHAT_PERMISSION_OPTIONS_NONE = 0u,
	PARTY_CHAT_PERMISSION_OPTIONS_SEND_MICROPHONE_AUDIO = 1u,
	PARTY_CHAT_PERMISSION_OPTIONS_SEND_TEXT_TO_SPEECH_AUDIO = 2u,
	PARTY_CHAT_PERMISSION_OPTIONS_SEND_AUDIO = 3u,
	PARTY_CHAT_PERMISSION_OPTIONS_RECEIVE_MICROPHONE_AUDIO = 4u,
	PARTY_CHAT_PERMISSION_OPTIONS_RECEIVE_TEXT_TO_SPEECH_AUDIO = 8u,
	PARTY_CHAT_PERMISSION_OPTIONS_RECEIVE_AUDIO = 12u,
	PARTY_CHAT_PERMISSION_OPTIONS_RECEIVE_TEXT = 16u
}
