using System;
using System.Diagnostics;
using System.Runtime.InteropServices;
using PartyCSharpSDK.Interop;

namespace PartyCSharpSDK;

public class PARTY_STATE_CHANGE
{
	protected bool useObjectPool;

	public PARTY_STATE_CHANGE_TYPE StateChangeType { get; }

	internal IntPtr StateChangeId { get; }

	protected PARTY_STATE_CHANGE(PARTY_STATE_CHANGE_TYPE StateChangeType, IntPtr StateChangeId)
	{
		this.StateChangeType = StateChangeType;
		this.StateChangeId = StateChangeId;
		useObjectPool = false;
	}

	internal static PARTY_STATE_CHANGE CreateFromPtr(IntPtr stateChangePtr)
	{
		PARTY_STATE_CHANGE pARTY_STATE_CHANGE = null;
		PARTY_STATE_CHANGE_UNION pARTY_STATE_CHANGE_UNION = (PARTY_STATE_CHANGE_UNION)Marshal.PtrToStructure(stateChangePtr, typeof(PARTY_STATE_CHANGE_UNION));
		switch (pARTY_STATE_CHANGE_UNION.stateChange.stateChangeType)
		{
		case PARTY_STATE_CHANGE_TYPE.PARTY_STATE_CHANGE_TYPE_REGIONS_CHANGED:
			return new PARTY_REGIONS_CHANGED_STATE_CHANGE(pARTY_STATE_CHANGE_UNION, stateChangePtr);
		case PARTY_STATE_CHANGE_TYPE.PARTY_STATE_CHANGE_TYPE_DESTROY_LOCAL_USER_COMPLETED:
			return new PARTY_DESTROY_LOCAL_USER_COMPLETED_STATE_CHANGE(pARTY_STATE_CHANGE_UNION, stateChangePtr);
		case PARTY_STATE_CHANGE_TYPE.PARTY_STATE_CHANGE_TYPE_CREATE_NEW_NETWORK_COMPLETED:
			return new PARTY_CREATE_NEW_NETWORK_COMPLETED_STATE_CHANGE(pARTY_STATE_CHANGE_UNION, stateChangePtr);
		case PARTY_STATE_CHANGE_TYPE.PARTY_STATE_CHANGE_TYPE_CONNECT_TO_NETWORK_COMPLETED:
			return new PARTY_CONNECT_TO_NETWORK_COMPLETED_STATE_CHANGE(pARTY_STATE_CHANGE_UNION, stateChangePtr);
		case PARTY_STATE_CHANGE_TYPE.PARTY_STATE_CHANGE_TYPE_AUTHENTICATE_LOCAL_USER_COMPLETED:
			return new PARTY_AUTHENTICATE_LOCAL_USER_COMPLETED_STATE_CHANGE(pARTY_STATE_CHANGE_UNION, stateChangePtr);
		case PARTY_STATE_CHANGE_TYPE.PARTY_STATE_CHANGE_TYPE_NETWORK_CONFIGURATION_MADE_AVAILABLE:
			return new PARTY_NETWORK_CONFIGURATION_MADE_AVAILABLE_STATE_CHANGE(pARTY_STATE_CHANGE_UNION, stateChangePtr);
		case PARTY_STATE_CHANGE_TYPE.PARTY_STATE_CHANGE_TYPE_NETWORK_DESCRIPTOR_CHANGED:
			return new PARTY_NETWORK_DESCRIPTOR_CHANGED_STATE_CHANGE(pARTY_STATE_CHANGE_UNION, stateChangePtr);
		case PARTY_STATE_CHANGE_TYPE.PARTY_STATE_CHANGE_TYPE_LOCAL_USER_REMOVED:
			return new PARTY_LOCAL_USER_REMOVED_STATE_CHANGE(pARTY_STATE_CHANGE_UNION, stateChangePtr);
		case PARTY_STATE_CHANGE_TYPE.PARTY_STATE_CHANGE_TYPE_REMOVE_LOCAL_USER_COMPLETED:
			return new PARTY_REMOVE_LOCAL_USER_COMPLETED_STATE_CHANGE(pARTY_STATE_CHANGE_UNION, stateChangePtr);
		case PARTY_STATE_CHANGE_TYPE.PARTY_STATE_CHANGE_TYPE_LOCAL_USER_KICKED:
			return new PARTY_LOCAL_USER_KICKED_STATE_CHANGE(pARTY_STATE_CHANGE_UNION, stateChangePtr);
		case PARTY_STATE_CHANGE_TYPE.PARTY_STATE_CHANGE_TYPE_CREATE_ENDPOINT_COMPLETED:
			return new PARTY_CREATE_ENDPOINT_COMPLETED_STATE_CHANGE(pARTY_STATE_CHANGE_UNION, stateChangePtr);
		case PARTY_STATE_CHANGE_TYPE.PARTY_STATE_CHANGE_TYPE_DESTROY_ENDPOINT_COMPLETED:
			return new PARTY_DESTROY_ENDPOINT_COMPLETED_STATE_CHANGE(pARTY_STATE_CHANGE_UNION, stateChangePtr);
		case PARTY_STATE_CHANGE_TYPE.PARTY_STATE_CHANGE_TYPE_ENDPOINT_CREATED:
			return new PARTY_ENDPOINT_CREATED_STATE_CHANGE(pARTY_STATE_CHANGE_UNION, stateChangePtr);
		case PARTY_STATE_CHANGE_TYPE.PARTY_STATE_CHANGE_TYPE_ENDPOINT_DESTROYED:
			return new PARTY_ENDPOINT_DESTROYED_STATE_CHANGE(pARTY_STATE_CHANGE_UNION, stateChangePtr);
		case PARTY_STATE_CHANGE_TYPE.PARTY_STATE_CHANGE_TYPE_REMOTE_DEVICE_CREATED:
			return new PARTY_REMOTE_DEVICE_CREATED_STATE_CHANGE(pARTY_STATE_CHANGE_UNION, stateChangePtr);
		case PARTY_STATE_CHANGE_TYPE.PARTY_STATE_CHANGE_TYPE_REMOTE_DEVICE_DESTROYED:
			return new PARTY_REMOTE_DEVICE_DESTROYED_STATE_CHANGE(pARTY_STATE_CHANGE_UNION, stateChangePtr);
		case PARTY_STATE_CHANGE_TYPE.PARTY_STATE_CHANGE_TYPE_REMOTE_DEVICE_JOINED_NETWORK:
			return new PARTY_REMOTE_DEVICE_JOINED_NETWORK_STATE_CHANGE(pARTY_STATE_CHANGE_UNION, stateChangePtr);
		case PARTY_STATE_CHANGE_TYPE.PARTY_STATE_CHANGE_TYPE_REMOTE_DEVICE_LEFT_NETWORK:
			return new PARTY_REMOTE_DEVICE_LEFT_NETWORK_STATE_CHANGE(pARTY_STATE_CHANGE_UNION, stateChangePtr);
		case PARTY_STATE_CHANGE_TYPE.PARTY_STATE_CHANGE_TYPE_LEAVE_NETWORK_COMPLETED:
			return new PARTY_LEAVE_NETWORK_COMPLETED_STATE_CHANGE(pARTY_STATE_CHANGE_UNION, stateChangePtr);
		case PARTY_STATE_CHANGE_TYPE.PARTY_STATE_CHANGE_TYPE_NETWORK_DESTROYED:
			return new PARTY_NETWORK_DESTROYED_STATE_CHANGE(pARTY_STATE_CHANGE_UNION, stateChangePtr);
		case PARTY_STATE_CHANGE_TYPE.PARTY_STATE_CHANGE_TYPE_ENDPOINT_MESSAGE_RECEIVED:
			return SDK.objectPool.Retrieve<PARTY_ENDPOINT_MESSAGE_RECEIVED_STATE_CHANGE>(pARTY_STATE_CHANGE_UNION, stateChangePtr);
		case PARTY_STATE_CHANGE_TYPE.PARTY_STATE_CHANGE_TYPE_CREATE_INVITATION_COMPLETED:
			return new PARTY_CREATE_INVITATION_COMPLETED_STATE_CHANGE(pARTY_STATE_CHANGE_UNION, stateChangePtr);
		case PARTY_STATE_CHANGE_TYPE.PARTY_STATE_CHANGE_TYPE_REVOKE_INVITATION_COMPLETED:
			return new PARTY_REVOKE_INVITATION_COMPLETED_STATE_CHANGE(pARTY_STATE_CHANGE_UNION, stateChangePtr);
		case PARTY_STATE_CHANGE_TYPE.PARTY_STATE_CHANGE_TYPE_INVITATION_CREATED:
			return new PARTY_INVITATION_CREATED_STATE_CHANGE(pARTY_STATE_CHANGE_UNION, stateChangePtr);
		case PARTY_STATE_CHANGE_TYPE.PARTY_STATE_CHANGE_TYPE_INVITATION_DESTROYED:
			return new PARTY_INVITATION_DESTROYED_STATE_CHANGE(pARTY_STATE_CHANGE_UNION, stateChangePtr);
		case PARTY_STATE_CHANGE_TYPE.PARTY_STATE_CHANGE_TYPE_KICK_DEVICE_COMPLETED:
			return new PARTY_KICK_DEVICE_COMPLETED_STATE_CHANGE(pARTY_STATE_CHANGE_UNION, stateChangePtr);
		case PARTY_STATE_CHANGE_TYPE.PARTY_STATE_CHANGE_TYPE_KICK_USER_COMPLETED:
			return new PARTY_KICK_USER_COMPLETED_STATE_CHANGE(pARTY_STATE_CHANGE_UNION, stateChangePtr);
		case PARTY_STATE_CHANGE_TYPE.PARTY_STATE_CHANGE_TYPE_CREATE_CHAT_CONTROL_COMPLETED:
			return new PARTY_CREATE_CHAT_CONTROL_COMPLETED_STATE_CHANGE(pARTY_STATE_CHANGE_UNION, stateChangePtr);
		case PARTY_STATE_CHANGE_TYPE.PARTY_STATE_CHANGE_TYPE_DESTROY_CHAT_CONTROL_COMPLETED:
			return new PARTY_DESTROY_CHAT_CONTROL_COMPLETED_STATE_CHANGE(pARTY_STATE_CHANGE_UNION, stateChangePtr);
		case PARTY_STATE_CHANGE_TYPE.PARTY_STATE_CHANGE_TYPE_CHAT_CONTROL_CREATED:
			return new PARTY_CHAT_CONTROL_CREATED_STATE_CHANGE(pARTY_STATE_CHANGE_UNION, stateChangePtr);
		case PARTY_STATE_CHANGE_TYPE.PARTY_STATE_CHANGE_TYPE_CHAT_CONTROL_DESTROYED:
			return new PARTY_CHAT_CONTROL_DESTROYED_STATE_CHANGE(pARTY_STATE_CHANGE_UNION, stateChangePtr);
		case PARTY_STATE_CHANGE_TYPE.PARTY_STATE_CHANGE_TYPE_CHAT_CONTROL_JOINED_NETWORK:
			return new PARTY_CHAT_CONTROL_JOINED_NETWORK_STATE_CHANGE(pARTY_STATE_CHANGE_UNION, stateChangePtr);
		case PARTY_STATE_CHANGE_TYPE.PARTY_STATE_CHANGE_TYPE_CHAT_CONTROL_LEFT_NETWORK:
			return new PARTY_CHAT_CONTROL_LEFT_NETWORK_STATE_CHANGE(pARTY_STATE_CHANGE_UNION, stateChangePtr);
		case PARTY_STATE_CHANGE_TYPE.PARTY_STATE_CHANGE_TYPE_CONNECT_CHAT_CONTROL_COMPLETED:
			return new PARTY_CONNECT_CHAT_CONTROL_COMPLETED_STATE_CHANGE(pARTY_STATE_CHANGE_UNION, stateChangePtr);
		case PARTY_STATE_CHANGE_TYPE.PARTY_STATE_CHANGE_TYPE_DISCONNECT_CHAT_CONTROL_COMPLETED:
			return new PARTY_DISCONNECT_CHAT_CONTROL_COMPLETED_STATE_CHANGE(pARTY_STATE_CHANGE_UNION, stateChangePtr);
		case PARTY_STATE_CHANGE_TYPE.PARTY_STATE_CHANGE_TYPE_SET_CHAT_AUDIO_INPUT_COMPLETED:
			return new PARTY_SET_CHAT_AUDIO_INPUT_COMPLETED_STATE_CHANGE(pARTY_STATE_CHANGE_UNION, stateChangePtr);
		case PARTY_STATE_CHANGE_TYPE.PARTY_STATE_CHANGE_TYPE_SET_CHAT_AUDIO_OUTPUT_COMPLETED:
			return new PARTY_SET_CHAT_AUDIO_OUTPUT_COMPLETED_STATE_CHANGE(pARTY_STATE_CHANGE_UNION, stateChangePtr);
		case PARTY_STATE_CHANGE_TYPE.PARTY_STATE_CHANGE_TYPE_LOCAL_CHAT_AUDIO_INPUT_CHANGED:
			return new PARTY_LOCAL_CHAT_AUDIO_INPUT_CHANGED_STATE_CHANGE(pARTY_STATE_CHANGE_UNION, stateChangePtr);
		case PARTY_STATE_CHANGE_TYPE.PARTY_STATE_CHANGE_TYPE_LOCAL_CHAT_AUDIO_OUTPUT_CHANGED:
			return new PARTY_LOCAL_CHAT_AUDIO_OUTPUT_CHANGED_STATE_CHANGE(pARTY_STATE_CHANGE_UNION, stateChangePtr);
		case PARTY_STATE_CHANGE_TYPE.PARTY_STATE_CHANGE_TYPE_POPULATE_AVAILABLE_TEXT_TO_SPEECH_PROFILES_COMPLETED:
			return new PARTY_POPULATE_AVAILABLE_TEXT_TO_SPEECH_PROFILES_COMPLETED_STATE_CHANGE(pARTY_STATE_CHANGE_UNION, stateChangePtr);
		case PARTY_STATE_CHANGE_TYPE.PARTY_STATE_CHANGE_TYPE_SET_LANGUAGE_COMPLETED:
			return new PARTY_SET_LANGUAGE_COMPLETED_STATE_CHANGE(pARTY_STATE_CHANGE_UNION, stateChangePtr);
		case PARTY_STATE_CHANGE_TYPE.PARTY_STATE_CHANGE_TYPE_CHAT_TEXT_RECEIVED:
			return new PARTY_CHAT_TEXT_RECEIVED_STATE_CHANGE(pARTY_STATE_CHANGE_UNION, stateChangePtr);
		case PARTY_STATE_CHANGE_TYPE.PARTY_STATE_CHANGE_TYPE_SET_CHAT_AUDIO_ENCODER_BITRATE_COMPLETED:
			return new PARTY_SET_CHAT_AUDIO_ENCODER_BITRATE_COMPLETED_STATE_CHANGE(pARTY_STATE_CHANGE_UNION, stateChangePtr);
		case PARTY_STATE_CHANGE_TYPE.PARTY_STATE_CHANGE_TYPE_SET_TEXT_CHAT_OPTIONS_COMPLETED:
			return new PARTY_SET_TEXT_CHAT_OPTIONS_COMPLETED_STATE_CHANGE(pARTY_STATE_CHANGE_UNION, stateChangePtr);
		case PARTY_STATE_CHANGE_TYPE.PARTY_STATE_CHANGE_TYPE_SET_TEXT_TO_SPEECH_PROFILE_COMPLETED:
			return new PARTY_SET_TEXT_TO_SPEECH_PROFILE_COMPLETED_STATE_CHANGE(pARTY_STATE_CHANGE_UNION, stateChangePtr);
		case PARTY_STATE_CHANGE_TYPE.PARTY_STATE_CHANGE_TYPE_SET_TRANSCRIPTION_OPTIONS_COMPLETED:
			return new PARTY_SET_TRANSCRIPTION_OPTIONS_COMPLETED_STATE_CHANGE(pARTY_STATE_CHANGE_UNION, stateChangePtr);
		case PARTY_STATE_CHANGE_TYPE.PARTY_STATE_CHANGE_TYPE_VOICE_CHAT_TRANSCRIPTION_RECEIVED:
			return SDK.objectPool.Retrieve<PARTY_VOICE_CHAT_TRANSCRIPTION_RECEIVED_STATE_CHANGE>(pARTY_STATE_CHANGE_UNION, stateChangePtr);
		case PARTY_STATE_CHANGE_TYPE.PARTY_STATE_CHANGE_TYPE_SYNTHESIZE_TEXT_TO_SPEECH_COMPLETED:
			return new PARTY_SYNTHESIZE_TEXT_TO_SPEECH_COMPLETED_STATE_CHANGE(pARTY_STATE_CHANGE_UNION, stateChangePtr);
		default:
			Debugger.Break();
			return new PARTY_STATE_CHANGE(pARTY_STATE_CHANGE_UNION.stateChange.stateChangeType, stateChangePtr);
		}
	}

	internal virtual void Cleanup()
	{
		if (useObjectPool)
		{
			SDK.objectPool.Return(this);
		}
	}
}
