namespace PartyCSharpSDK;

public enum PARTY_TEXT_CHAT_OPTIONS : uint
{
	PARTY_TEXT_CHAT_OPTIONS_NONE,
	PARTY_TEXT_CHAT_OPTIONS_TRANSLATE_TO_LOCAL_LANGUAGE,
	PARTY_TEXT_CHAT_OPTIONS_FILTER_OFFENSIVE_TEXT
}
